COMPONENT_RENDERER = "renderer"
COMPONENT_SPRITE_RENDERER = "sprite_renderer"
COMPONENT_TEXT_RENDERER = "text_renderer"
COMPONENT_TRANSFORM = "transform"
COMPONENT_PHYSICS_RIGID_BODY2D = "rigid_body_2d"
COMPONENT_PHYSICS_BOX_COLLIDER2D = "box_collider_2d"
COMPONENT_SCRIPT = "script"

DEBUG_DRAW = 0
NORMAL_DRAW = 1